#!/bin/bash
set -o pipefail
set -e
set -f

source /usr/local/etc/babun/source/babun-core/tools/procps.sh
source /usr/local/etc/babun/source/babun-core/tools/check.sh
check_only_one_running "/usr/local/bin/babun"

function usage()
{
  echo babun: Manages the instance of babun.
  echo ""
  echo "Usage:"
  echo "  \"babun update\" to fetch the newest version of babun"  
  echo "  \"babun check\" to check if the installation is correct"  
  echo "Options:"
  echo "  --help"
  echo "  --version"
  echo "  --welcome"
}

function version()
{
  echo "babun version 1.0.0"
  echo "Created and maintained by Tom Bujok (@tombujok)"
  echo "Copyright (c) 2014."
}

function welcome()
{
  echo -e "Welcome to babun - the Windows shell you will love!"
  echo -e "You have got a lot of things under the hood here!"
  echo -e ""
  echo -e "   pact -> a package manager that handles installation of babun packages"
  echo -e "      pact install tar -> will install tar package on your system"
  echo -e "      pact remove tar -> will remove tar package from your system"
  echo -e ""
  echo -e "   babun -> a script that manages babun and enables auto-update"
  echo -e "      babun check -> will check the configuration (proxy, connection, etc)"
  echo -e "      babun update -> will update babun to the newest version"
  echo -e "      babun --welcome -> will display this message again"
  echo -e ""
  echo -e "Babun has a plugin architecture."
  echo -e "There's a couple of plugins installed by default: oh-my-zsh, pact, cacert, etc."
  echo -e "If you would like to contribute, code up a plugin or report an issue just"
  echo -e "go to github: https://github.com/babun/babun"
  echo -e ""
  echo -e "If you like the project star it on github and follow me on twitter!"
  echo -e "This project is created and maintained by Tom Bujok (@tombujok)"
}

#babun
core="/usr/local/etc/babun/source/babun-core"

# process options
noscripts=0
update=0
file=""
command=""
filepackages=""
packages=""

while test $# -gt 0
do
  case "$1" in

    --help)
      usage
      exit 0
    ;;

    --version)
      version
      exit 0
    ;;

    --welcome)
      welcome
      exit 0
    ;;


    update|check)
      if test "-$command-" = "--"
      then
        command=$1     
      fi
      shift

    ;;

    *)
	  usage
	  exit 1

    ;;

  esac
done


function update() 
{
  echo "Executing babun update"
  exec "$core"/tools/update_source.sh
  exit 0
}

function check() 
{
    echo "Executing babun check"
    babun_check
}


case "$command" in

  update)
  
  	update
  ;;


  check)

    check
  ;;


  *)

    usage

  ;;

esac


