#!/bin/bash
set -o pipefail
set -e
set -f

function usage()
{
  echo babun: Manages the instance of babun.
  echo ""
  echo "Usage:"
  echo "  \"babun update\" to fetch the newest version of babun"  
  echo "  \"babun check\" to check if the installation is correct"  
  echo "Options:"
  echo "  --help"
  echo "  --version"
}

function version()
{
  echo "babun version 1.0.0"
  echo "Created and maintained by Tom Bujok (@tombujok)"
  echo "Copyright (c) 2014."
}


#babun
core="/usr/local/etc/babun/source/babun-core"

# process options
noscripts=0
update=0
file=""
command=""
filepackages=""
packages=""

while test $# -gt 0
do
  case "$1" in

    --help)
      usage
      exit 0
    ;;

    --version)
      version
      exit 0
    ;;


    update|check)
      if test "-$command-" = "--"
      then
        command=$1     
      fi
      shift

    ;;

    *)
	  usage
	  exit 1

    ;;

  esac
done


function update() 
{
  echo "Updating babun!"
  "$core"/tools/upgrade_source.sh
  "$core"/tools/install.sh
  "$core"/tools/install_home.sh
}

function check() 
{
  echo "Checking the instance of babun!"
  echo "TODO - not implemented yet! Let's hope everything is fine :)"
}


case "$command" in

  update)
  
  	update
  ;;


  check)

    check
  ;;


  *)

    usage

  ;;

esac


