
=== Frequent Asked Questions

==== I cloned babun from github but when i try to start it I get some weird error message

You have to download the distribution package from http://projects.reficio.org/babun/babun-dist.zip[here].
On github we only host raw source files. The dist package is enriched by cygwin and some other stuff you need to run Babun.

==== How can I uninstall Babun?

Why would you :-) Seriously, just delete the .babun folder (by default installed in %USER_HOME%).

==== The daily babun check sometimes complains that 'my prompt is very slow'

Sometimes the prompt is slow when you start babun as the initialization and loading of dll's take time. You are find with that.

==== Old version of Git doesn't like my .gitconfig

If you run git in Babun and get error like this

----
git clone git@github.com:Painted-Fox/docker-postgresql.git
Cloning into 'docker-postgresql'...
error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 11 in /cygdrive/c/Users/ryan.seto/.gitconfig
----

The fix is described http://stackoverflow.com/questions/14330050/how-to-get-git-1-8-in-cygwin[here].

==== When I run git status in git shell and in babun I get different results

It is probably an end-of-line issue. Execute +git config --list+ both in cmd and in babun and compare the core.autocrlf value. If your cmd prints +core.autocrlf = true+ execute +git config --global core.autocrlf true+ in Babun.

==== How do I install gvm tool

* download gvmtool: +curl -s get.gvmtool.net | bash+
* edit .bash_profile, .bashrc and .zshrc and replace all occurrences of +/c/Users/...+ with +/cygdrive/c/Users/...+
* restart babun