

=== Features in 10 seconds

Babun features the following:

* Pre-configured Cygwin with a lot of addons
* Silent command-line installer, no admin rights required
* pact - advanced package manager (like apt-get or yum)
* xTerm-256 compatible console
* HTTP(s) proxying support
* Plugin-oriented architecture
* Pre-configured git and shell
* Integrated oh-my-zsh
* Auto update feature

=== Features in 3 minutes

==== Cygwin

The core of Babun consists of a pre-configured Cygwin. Cygwin is a great tool, but there's a lot of quirks and tricks that makes you loose a lot of time to make it actually 'usable'. Not only does babun solve most of these problems, but also contains a lot of vital packages, so that you can be productive from the very first minute. 

==== Package manager

Babun provides a package manager called +pact+. It is similar to 'apt-get' or 'yum'. Pact enables installing/searching/upgrading and deinstalling cygwin packages with no hassle at all. Just invoke +pact --help+ to check how to use it.

==== Shell

Babun's shell is tweaked in order to provide the best possible user-experience. There are two shell types that are pre-configured and avaiable right away - bash and zsh (zsh is the default one). Babun's shell features:

* syntax highlighting
* unix tools
* software development tools
* git-aware prompt 
* custom scripts and aliases
* and much more!

==== Console

Mintty is the console used in babun. It features an +xterm-256+ mode, nice fonts and simply looks great!

==== Proxying

Babun supports HTTP proxying out of the box. Just add the address and the credentials of your HTTP proxy server to the +.babunrc+ file located in your home folder and execute +source .babunrc+ to enable HTTP proxying. SOCKS proxies are not supported for now.

==== Developer tools

Babun provides many packages, convenience tools and scripts that make your life much easier. The long list of features includes:
* programming languages (python, perl, groovy, etc.)
* git (with a wide variety of aliases and tweaks)
* unix tools (grep, wget, curl, etc.)
* oh-my-zsh
* custom scripts (pbcopy, pbpaste, babun, etc.)

==== Plugin architecture

Babun has a very small microkernel (cygwin, a couple of bash scripts and a bit of a convention) and a plugin architecture on the top of it. It means that almost everything is a plugin in the babun's world! Not only does it structure babun in a clean way, but also enables others to contribute small chunks of code. Currently, babun comprises of six plugins:

* cacert
* core
* git
* oh-my-zsh
* pact
* shell

==== Auto-update

Self-update is at the very heart of babun! Many Cygwin tools are simple bash scripts - once you install them there is no chance of getting the newer version in a smooth way. You either delete the older version or overwrite it with the newest one loosing all the changes you have made in between.

Babun contains an auto-update feature which enables updating both the microkernel and the plugins. Files located in your home folder will not be delted nor overwritten which preserves your local config and customizations.

==== Installer

Babun features an silent command-line installation script that may be executed without admin rights on any Windows hosts.


=== Using babun

==== Setting up proxy
To setup proxy uncomment following lines in the +.babunrc+ file +(%USER_HOME%\.babun\cygwin\home\USER\.babunrc)+
----
# Uncomment this lines to set up your proxy
# export http_proxy=http://user:password@server:port
# export https_proxy=$http_proxy
# export ftp_proxy=$http_proxy
# export no_proxy=localhost
----

==== Installing new packages
Babun is shipped with +pact+ - a Linux like package manager. It uses the cygwin repository for downloading packages:
----
{ ~ } » pact install arj                                                                     ~ 1
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing arj
Found package arj
--2014-03-30 19:34:38--  http://mirrors.kernel.org/sourceware/cygwin//x86/release/arj/arj-3.10.22-1.tar.bz2
Resolving mirrors.kernel.org (mirrors.kernel.org)... 149.20.20.135, 149.20.4.71, 2001:4f8:1:10:0:1994:3:14, ...
Connecting to mirrors.kernel.org (mirrors.kernel.org)|149.20.20.135|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189944 (185K) [application/x-bzip2]
Saving to: `arj-3.10.22-1.tar.bz2'

100%[==========================================================>] 189,944      193K/s   in 1.0s

2014-03-30 19:34:39 (193 KB/s) - `arj-3.10.22-1.tar.bz2' saved [189944/189944]

Unpacking...
Package arj installed
----

==== Using git
Babun has a pre-configured git. The only thing you should do after installation is to add your name and email to the git config:
----
git config --global user.name "your name"
git config --global user.email "your@email.com"
----

==== .oh-my-zsh
Babun has an integrated +.oh-my-zsh+ plugin. The zsh is the default shell in babun. You can still change it to bash if you wish.
TODO - explain how to setup default shell

==== Updates
Babun checks every time at start up if a new version is available. You can also enforce it by typing:
----
babun check
----

To update babun to a newest version type:
----
babun update
----
Please note that your local configuration files will not be overwritten. 
